# Generated by Django 3.1.4 on 2021-01-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='books',
            name='year',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_ad',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
