# Generated by Django 3.1.4 on 2021-01-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210120_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='is_favorites',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.CharField(max_length=4),
        ),
    ]
